from matplotlib import pyplot as plt
import pandas as pd

import argparse


if __name__ == '__main__':

    parser = argparse.ArgumentParser(description='Plots a csv file generated by the training script')
    parser.add_argument('csv_file')
    parser.add_argument('--output_file')

    args = parser.parse_args()

    df = pd.read_csv(args.csv_file, index_col='episode_id')

    mdp = df.iloc[0]['arg_mdp']
    if 'arg_sokoban_level_name' in df.columns:
        mdp_params = df.iloc[0]['arg_sokoban_level_name']
    elif 'arg_blocks_world_size' in df.columns:
        mdp_params = df.iloc[0]['arg_blocks_world_size']
    else:
        mdp_params = ''

    control_algorithm = df.iloc[0]['arg_control_algorithm']


    plt.plot(df['behavior_policy_return'], label='Behavior policy')

    plt.plot(df['target_policy_return'], label='Target policy')
    plt.legend()
    plt.title(f'MDP={mdp} {mdp_params}\nControl={control_algorithm}')
    plt.tight_layout()
    if args.output_file:
        plt.savefig(args.output_file)
    plt.show()
